apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-fvzq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-fvzq
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-fvzq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-fvzq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-fvzq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-sorf-tenant/appstudio/devfile-sample-python-basic-fvzq@sha256:b8bb9442d5bf5d1a38eacb22b62025b7f51dd6b4d33bc5572250ab6558f4de0d
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
